### PR TITLE
Team

### LINKED ISSUE #3: Create Team page
Create team page from the template ./team.html
Inspiration from https://moodi.org/contact/marketing or last year anwesha team page, or celesta team page.
Search for a nice CodePen.

### PR DESCRIPTION
**Pull request by Ankit7Das**
fix #3

### CODE REVIEW

**Comment by ashwaniYDV** [comment]
@Ankit-717 Please add screenshots of the team page you added.

**Comment by Ankit7Das** [comment]
team
team1

**Comment by Subhang23** [comment]
@Ankit7Das Can you add the picture of the events(technical,arts and cultural) committee also?

**Comment by Ankit7Das** [comment]
@Subhang23 I sure can do it. But is it a committee to be inculcated into the team page?

**Comment by Subhang23** [comment]
There are 3 separate event organizing committees as mentioned above which should be added

**Comment by Ankit7Das** [comment]
Bhaiya I'll just need the info and I'll do it ASAP

**Comment by Subhang23** [comment]
I will send the information and the photos

**Pull request merged**
