### PR TITLE
fixed background image issue

### PR DESCRIPTION
**Pull request by Darshilp326**

### CODE REVIEW

**Comment by Subhang23** [comment]
@Darshilp326  Please attach a screenshot of the changes made

**Comment by Darshilp326** [comment]
Screenshot (8)

**Comment by ashwaniYDV** [comment]
@Darshilp326 You have created multiple commits in this PR.
But we only require "fixed background image issue" this one here.
Try to solve separate issues in separate branches.

**Comment by ashwaniYDV** [comment]
@Darshilp326 Also try to attach gif for the change if possible to record the screen just as I dit in making the issue after you have solved the issue.

**Pull request closed without merging**
